6 sgh
gsainfoteam/vapor-auth-be pull request #11
Opened 2024-03-15 16:01 UTC by GanghyeonSeo

2024-03-15 17:03 UTC, siwonpada requested changes

2024-03-15 17:03 UTC, siwonpada commented on src/group/group.controller.ts
> +  @Patch()
':uuid' + @Param 를 이용해서 update할 객체를 url에서 선택할 수 있도록 하는 것은 어떤가요?

2024-03-15 17:03 UTC, siwonpada commented on src/group/group.controller.ts
> +  @Delete()
위의 patch과 같이 url을 통해 수정이 될 객체를 보여주는 것은 어떨 까요?

2024-03-15 17:43 UTC, GanghyeonSeo commented on src/group/group.controller.ts
> +  @Patch()
/group/:uuid말고 /group/:name 사용해도 될까요?

2024-03-15 17:50 UTC, siwonpada commented on src/group/group.controller.ts
> +  @Patch()
Unique 걸려있는 거면 뭐든 상관 없습니다.

2024-03-16 03:53 UTC, siwonpada approved these changes

2024-03-16 03:53 UTC, siwonpada commented
merge 해도 될 것 같습니다.

2024-03-16 05:02 UTC, merged