10 jhc
gsainfoteam/vapor-auth-be pull request #16
Opened 2024-03-21 04:12 UTC by rabo8497

test code 작동 확인 - group create 기능
user-role 삭제 기능 추가

2024-03-24 04:42 UTC, siwonpada requested changes

2024-03-24 04:42 UTC, siwonpada commented on test/group/group.repository.spec.ts
> +  describe('createGroup', () => {
혹시 테스트 코드는 더 없나요?

2024-03-24 19:06 UTC, rabo8497 commented on test/group/group.repository.spec.ts
> +  describe('createGroup', () => {
추가한 코드가 있어서 다시 PR 날립니다.

2024-04-23 04:25 UTC, siwonpada approved these changes

2024-04-23 04:27 UTC, siwonpada commented
주석 처리한 것을 아예 삭제하고 conflict 해결 한 다음에 merge하면 될 것 같습니다.

2024-04-24 08:18 UTC, merged